---
title: "peptideprotonet_PIP_evals"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# load("HeLa_4rep_30min_peptideprotonet_evals.RData")
# load("HeLa_4rep_30min_peptideprotonet_evals_normalisedIntensity.RData")
load("HeLa_4rep_30min_peptideprotonet_evals_normalisedIntensity_sumTopN.RData")
dt_k3

cv_results_k3

library(ggplot2)
library(ggsci)


ggdat <- cv_results_k5
ggdat[7,1] <- gsub("MaxQuant-MBR", "MaxQuant MBR-", ggdat[7,1])
ggdat <- ggdat[ggdat$threshold %in% c(0, 0.01, 0.2, 0.5, 0.8, "MaxQuant MBR-"),]


ggdat$threshold[!grepl("Max", ggdat$threshold)] <- paste("peptideprotonet + PIP, thr=", 
                                                         ggdat$threshold[!grepl("Max", ggdat$threshold)],
                                                         sep="")

ggdat$threshold <- factor(ggdat$threshold, levels = c("MaxQuant MBR-",
                                                      "peptideprotonet + PIP, thr=0.8",
                                                      "peptideprotonet + PIP, thr=0.5",
                                                      "peptideprotonet + PIP, thr=0.2",
                                                      "peptideprotonet + PIP, thr=0.01",
                                                      "peptideprotonet + PIP, thr=0"
                                                      ))


ggdat <- reshape2::melt(ggdat, id = c("threshold", "total_idents"))
ggdat$variable <- as.factor(ggdat$variable)


# ggplot(ggdat, aes(x = threshold, y = value*100, fill = variable)) +
#   geom_bar(position = "dodge", stat = "identity") +
#   scale_y_continuous(
#     
#     # Features of the first axis
#     name = "CV (percent)",
#     
#     # Add a second axis and specify its features
#     sec.axis = sec_axis( trans=~.*1, name="Completemess (percent)")
# ) + theme_bw() + scale_fill_npg() +
#   xlab("Confidence threshold") + 
#   theme(
#     #legend.position = "None",
#         axis.text=element_text(colour="black", size = 12))

class(ggdat$threshold)

variable_names <- c("CV (peptide)", "CV (protein)", "Data completeness")
names(variable_names) <- c("CV_peptide","CV_protein", "complete_cases")


# to change the axis limits, setting it from 0 to 5% for CV or 100% for completeness
ggdat_blank <- data.frame(threshold = ggdat$threshold, variable = ggdat$variable)
ggdat_blank$value[grepl("CV", ggdat_blank$variable)] <- 0.05
ggdat_blank$value[grep("CV", ggdat_blank$variable, invert = TRUE)] <- 1

ggdat_blank[3,3] <- 0
ggdat_blank[16,3] <- 0
ggdat_blank[10,3] <- 0


ggplot(ggdat, aes(x = threshold, y = value*100, fill = variable, color = variable)) +
#   geom_bar(position = "dodge", stat = "identity") +
#   scale_y_continuous(
#     
#     # Features of the first axis
#     name = "CV (percent)",
#     
#     # Add a second axis and specify its features
#     sec.axis = sec_axis( trans=~.*1, name="Completemess (percent)")
# ) +
  
  geom_dotplot(binaxis='y', stackdir='center',
                dotsize=2) +
  coord_flip()+
  facet_wrap(.~variable, scale = "free_x",
              labeller = labeller(variable = variable_names)) +
  
  theme_linedraw() + 
  scale_fill_brewer(palette = "Set1") +
  scale_color_brewer(palette = "Set1") +
  geom_blank(data = ggdat_blank) + 
  #xlab("Confidence threshold") + 
  xlab("") +
  ylab("Percent (%)") +
  ggtitle("Peptide/protein median coefficient of variation (CV) and data completeness \nin four HeLa cell lysate Replicates (N = 53639 identifications)") +
  theme(
    plot.title = element_text(hjust = 0.5),
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    strip.text.x = element_text(
        size = 14,
        face = "bold"
        ),
    legend.position = "None",
        axis.text=element_text(colour="black", size = 12)) 





```


```{r}
library(kableExtra)

load("tcells_exosome_peptideprotonet_evals.RData")
load("HeLa_10rep_2hr_peptideprotonet_evals_normalisedIntensity.RData")


dt <- rbind(cbind(dt_k5[, grep("max|mean_coverage$", colnames(dt_k5), invert = TRUE)], 
                  dt_k5_tcells[, grep("threshold|max|mean_coverage$", colnames(dt_k5_tcells), invert = TRUE)]),
            cbind(dt_k10[, grep("max|mean_coverage$", colnames(dt_k10), invert = TRUE)], 
                  dt_k10_tcells[, grep("threshold|max|mean_coverage$", colnames(dt_k10_tcells), invert = TRUE)])
)


dt[,2] <- dt[,2] * 100
dt[,2] <- paste0(dt[,2], "%")



dt[,6] <- dt[,6] * 100
dt[,6] <- paste0(dt[,6], "%")

dt[,8] <- as.character(dt[,8])
dt[,4] <- as.character(dt[,4])

dt <- apply(dt, 2, as.character)

```

```{r}
kbl(dt, 
    format = "latex",
    booktabs = T,
    #longtable = T,
    caption = "False transfer rate and peptide coverage per run",
    col.names = c("Threshold",
                  "False transfer rate", #"False transfer rate", 
                  "Mean Coverage", #"Mean coverage after PIP",
                  "New identifications",  #"Number new identifications", 
                  "Median identifications", #"Median identifications per run",
                  "False transfer rate",
                  "Mean coverage",
                    "New identifications",
                  "Median identifications"
                  )
    # row.names = paste("threshold", dt$threshold)
    ) %>%
add_header_above(c(" ", "HeLa cell lysate replicates 2hr gradient (n = 10)[note]" = 4, "T cells OSCC (n = 6)[note]" = 4)) %>%
  pack_rows("k = 5", 1, 6) %>%
pack_rows("k = 10", 7, 12) %>%
  kable_styling(latex_options = c("scale_down"), full_width = T, position = "center") %>%
  column_spec(c(2,6), width = "4em") %>%
  column_spec(c(3:5, 7:9), width = "4em") %>%
  footnote(general = "The figures are based on peptide identifications per run.") %>%
  add_footnote(
    # general = "The figures are based on peptide identifications per run. Total identifications is the median of new and transferred peptide identifications per run.",
# number = c("Footnote 1; ", "Footnote 2; "),
# alphabet = c("Footnote A; ", "Footnote B; "),
# symbol = c("Mean peptide coverage reported by MaxQuant is 0.67 before PIP; ", 
#            "Mean peptide coverage reported by MaxQuant is 0.54 before PIP")
    
 c("Mean peptide coverage reported by MaxQuant is 0.67 before PIP; ",
           "Mean peptide coverage reported by MaxQuant is 0.54 before PIP"),
    
    notation = "symbol"
 ) 

# save_kable("peptideprotonet_PIP_false_transfer_evals.png")
# save_kable("my_latex_table.png")
```


```{r}


dt <- rbind(cv_results_k5, cv_results_k10)
dt <- dt[!duplicated(dt),]
dt$threshold <-  gsub("MQ\\+MBR", "MaxQuant MBR\\+", dt$threshold)
dt <- rbind(dt[7, ,drop=FALSE], dt[1:6,], dt[8:13,])

rownames(dt)[1] <- dt$threshold[1]
rownames(dt)[2:7] <- paste("peptideprotonet + PIP; k=5; thr=", dt$threshold[2:7])
rownames(dt)[8:13] <- paste("peptideprotonet + PIP; k=10; thr=", dt$threshold[8:13])

dt$threshold <- NULL

dt$CV_peptide <- dt$CV_peptide * 100
dt$CV_peptide <- paste0(dt$CV_peptide, "%")


dt$complete_cases <- dt$complete_cases * 100
dt$complete_cases <- paste0(dt$complete_cases, "%")

# rownames(dt)[1:6] <- paste("peptideprotonet + PIP thresh=", dt$threshold[1:6], sep="")
# rownames(dt)[7] <- "MaxQuant+MBR"




load("HeLa_10rep_2hr_peptideprotonet_evals_normalisedIntensity_nquantprotein.RData")

dt2 <- c(cv_results_k5$n_quant_proteins[7], 
         cv_results_k5$n_quant_proteins[1:6],
         cv_results_k10$n_quant_proteins[1:6])


# dt <- cbind(dt, dt2)
dt$nprotein <- c(cv_results_k5$n_quant_proteins[7], 
         cv_results_k5$n_quant_proteins[1:6],
         cv_results_k10$n_quant_proteins[1:6])

#dt <- apply(dt, 2, as.character)
dt <- data.frame(dt)
dt$total_idents <- as.character(dt$total_idents)
dt$nprotein <- as.character(dt$nprotein)

# dt <- rbind(dt[2:13,], dt[1,, drop=FALSE])
# dt$name <- rownames(dt)

kbl(dt, 
    booktabs = T, 
    # escape = F,
    #longtable = T,
    caption = linebreak("Peptide coverage, coefficient of variation (CV) and data completeness\\\\in ten HeLa cell lysate replicates", align = "c"),
    col.names = c("CV", "total identifications", "data completeness","quantified proteins")
    ) %>%
  # column_spec(c(3:4), width = "4.2em") %>%
  column_spec(5, width = "4em") %>%
# add_header_above(c( "k=5" = 3, "k= 10" = 4)) %>%
  pack_rows("peptideprotonet + PIP; k = 5", 3, 8) %>%
pack_rows("peptideprotonet + PIP; k = 10", 9, 13) %>%
  kable_styling() #latex_options = c("scale_down")
```

Heatmap for Tcells dataset based on the above results:
```{r}


```
