---
title: "false_transfer_evaluations_for_peptideprotonet"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
# data <- read.csv("~/ion_mobility/peptideprotonet_embedding_space_90Kto20KsplitTrain_epoch300_featuresScaled_tcells_cancer_query_icml2021.csv")

query_embedding <- read.csv('~/ion_mobility/peptideprotonet_embedding_space_90Kto20KsplitTrain_epoch300_featuresScaled_TCellsCancer_noEvidenceTrain.csv')

refrence_data <- read.csv('~/ion_mobility/peptideprotonet_embedding_space_90Kto20KsplitTrain_epoch300_featuresScaled_EvidenceTrain.csv')

tcells_evidence <- read.delim("~/ion_mobility/PXD023049/txt/evidence.txt")
tcells_evidence$PrecursorID <- paste(tcells_evidence$Modified.sequence, tcells_evidence$Charge, sep="")
tcells_evidence$Species <- "Human"

query <- query_embedding # grep("dim|Raw.file", colnames(data))
reference <- refrence_data #  grep("dim", colnames(data))
query$Raw.file.id <- as.numeric(as.factor(query$Raw.file))
tcells_evidence$Raw.file.id <- as.numeric(as.factor(tcells_evidence$Raw.file))


lc_ms_anchors  <- c("Raw.file.id", "Charge","m.z", "Mass", "Intensity","Retention.time")
identified_peptides <- FNN::get.knnx(query[, lc_ms_anchors], tcells_evidence[, lc_ms_anchors], k=1)
identified_peptides <- query[identified_peptides$nn.index,]
identified_peptides$PrecursorID <- tcells_evidence$PrecursorID
identified_peptides$Species <- tcells_evidence$Species


unidentified_peptides <- dplyr::anti_join(query, identified_peptides,
                                            by = lc_ms_anchors)



reference_combined <- rbind(reference[,c(grep("dim", colnames(reference), value = TRUE), "Charge", "PrecursorID", "Species")],
                            identified_peptides[,c(grep("dim", colnames(reference), value = TRUE), "Charge" ,"PrecursorID", "Species")])
                            
unidentified_peptides_latent <- unidentified_peptides[, grep("dim", colnames(unidentified_peptides))]


reference_latent <- reference_combined[, grep("dim", colnames(reference_combined))]
reference_charge <- reference_combined$Charge
reference_ident_labels <- reference_combined$PrecursorID
reference_ident_species <- reference_combined$Species


all_unidentified_peptides <- unidentified_peptides
```

```{r}

query_feature_charges <- unidentified_peptides$Charge


k = 15

knn_prototypes <- FNN::get.knnx(

      
      reference_latent,
      unidentified_peptides_latent,
      k = k) # nsamples - 1


    
# probs <- exp(-0.5*((knn_prototypes$nn.dist^2)/matrixStats::rowSds(knn_prototypes$nn.dist^2)))
probs <- knn_prototypes$nn.index

ww <- matrix(reference_charge[knn_prototypes$nn.index], nrow = nrow(probs), ncol = ncol(probs))
charge <- matrix(query_feature_charges, nrow = nrow(ww), ncol = ncol(ww), byrow = FALSE)
w <- ifelse(ww==charge, 1, 0)

transferred_idents <- matrix(reference_ident_labels[knn_prototypes$nn.index], nrow = nrow(probs), ncol = ncol(probs))
transferred_species <- matrix(reference_ident_species[knn_prototypes$nn.index], nrow = nrow(probs), ncol = ncol(probs))

table(rowSums(transferred_species == "Yeast") == 15)
table(rowSums(transferred_species == "Yeast") > 10)
table(rowSums(transferred_species == "Yeast") > 7)

# which of the peptides with high p of being identified as yeast share a neighbourhood with an identified peptide in the same run?

## mapping between identified peptides and unidentified peptides by closeness of their LC-MS features
dentified_peptides <- FNN::get.knnx(identified_peptides[, grep("Intensity", lc_ms_anchors, invert=TRUE, value = TRUE)], 
                                    unidentified_peptides[, grep("Intensity", lc_ms_anchors, invert=TRUE, value = TRUE)], 
                                    k=3)




probs <- exp(-0.5*((dentified_peptides$nn.dist^2)/matrixStats::rowSds(dentified_peptides$nn.dist^2)))

table(probs[,1] > 0.5 & rowSums(transferred_species == "Yeast") > 7)
table(probs[,1] > 0.8 & rowSums(transferred_species == "Yeast") > 7)

## compute false transfers as ratio of yeast transfers to human transfers per run 
false_transfers <- (probs[,1] > 0.5 & rowSums(transferred_species == "Yeast") > 7)
correct_transfers <-  (probs[,1] > 0.5 & rowSums(transferred_species == "Human") > 7)

correct_transfers_run_names <- unidentified_peptides$Raw.file[correct_transfers]
false_transfers_run_names <- unidentified_peptides$Raw.file[false_transfers]
total_transfers_run_names <- unidentified_peptides$Raw.file[probs[,1] > 0.5]

table(false_transfers_run_names)/table(correct_transfers_run_names)
table(false_transfers_run_names)/table(total_transfers_run_names)

#########################
# what proportion of human idents whould be mapped as non-human (say, yeast, for example)
###########################


reference_latent <- reference[, grep("dim", colnames(reference))]
reference_charge <- reference$Charge
reference_ident_labels <- reference$PrecursorID
reference_ident_species <- reference$Species

identified_peptides_latent <- identified_peptides[, grep("dim", colnames(identified_peptides))]
query_feature_charges <- identified_peptides$Charge


k = 15

knn_prototypes <- FNN::get.knnx(

      
      reference_latent,
      identified_peptides_latent,
      k = k) # nsamples - 1


    
# probs <- exp(-0.5*((knn_prototypes$nn.dist^2)/matrixStats::rowSds(knn_prototypes$nn.dist^2)))
probs <- knn_prototypes$nn.index

ww <- matrix(reference_charge[knn_prototypes$nn.index], nrow = nrow(probs), ncol = ncol(probs))
charge <- matrix(query_feature_charges, nrow = nrow(ww), ncol = ncol(ww), byrow = FALSE)
w <- ifelse(ww==charge, 1, 0)

transferred_idents <- matrix(reference_ident_labels[knn_prototypes$nn.index], nrow = nrow(probs), ncol = ncol(probs))
transferred_species <- matrix(reference_ident_species[knn_prototypes$nn.index], nrow = nrow(probs), ncol = ncol(probs))

table(rowSums(transferred_species == "Yeast") == 15)
table(rowSums(transferred_species == "Yeast") > 10)
table(rowSums(transferred_species == "Yeast") > 7)


false_transfers <- (rowSums(transferred_species == "Yeast") > 7)
false_transfers_run_names <- identified_peptides$Raw.file[false_transfers]



correct_transfers <-  (rowSums(transferred_species == "HeLa") > 7)
correct_transfers_run_names <- identified_peptides$Raw.file[correct_transfers]



table(false_transfers_run_names)/table(correct_transfers_run_names)



####### ##
# v.s.
#######


reference_latent <- reference_combined[, grep("dim", colnames(reference_combined))]
reference_latent <- reference_combined[reference_combined$Species %in% c("HeLa","Human","Yeast"), ]
reference_charge <- reference_combined$Charge
reference_ident_labels <- reference_combined$PrecursorID
reference_ident_species <- reference_combined$Species

identified_peptides_latent <- identified_peptides[, grep("dim", colnames(identified_peptides))]
query_feature_charges <- identified_peptides$Charge


k = 15

knn_prototypes <- FNN::get.knnx(

      
      reference_latent,
      identified_peptides_latent,
      k = k) # nsamples - 1


    
# probs <- exp(-0.5*((knn_prototypes$nn.dist^2)/matrixStats::rowSds(knn_prototypes$nn.dist^2)))
probs <- knn_prototypes$nn.index

ww <- matrix(reference_charge[knn_prototypes$nn.index], nrow = nrow(probs), ncol = ncol(probs))
charge <- matrix(query_feature_charges, nrow = nrow(ww), ncol = ncol(ww), byrow = FALSE)
w <- ifelse(ww==charge, 1, 0)

transferred_idents <- matrix(reference_ident_labels[knn_prototypes$nn.index], nrow = nrow(probs), ncol = ncol(probs))
transferred_species <- matrix(reference_ident_species[knn_prototypes$nn.index], nrow = nrow(probs), ncol = ncol(probs))

table(rowSums(transferred_species == "Yeast") == 15)
table(rowSums(transferred_species == "Yeast") > 10)
table(rowSums(transferred_species == "Yeast") > 7)


false_transfers <- (rowSums(transferred_species == "Yeast") > 7)
false_transfers_run_names <- identified_peptides$Raw.file[false_transfers]



correct_transfers <-  (rowSums(transferred_species == "Human") > 7)
correct_transfers_run_names <- identified_peptides$Raw.file[correct_transfers]



table(false_transfers_run_names)/table(correct_transfers_run_names)
median(table(false_transfers_run_names)/table(correct_transfers_run_names))




## compute prototypes


## compute probabilities as kernel function of distance to prototype

## label is the most confident assignment

```

```{r}
### this chuck implements the two-pass approach

# reference_combined <- rbind(reference[,c(grep("dim", colnames(reference), value = TRUE), "Charge", "PrecursorID", "Species")],
#                             identified_peptides[,c(grep("dim", colnames(reference), value = TRUE), "Charge" ,"PrecursorID", "Species")])
                            
# reference_combined <- reference_combined[grep("ox|Deamidation|Acetyl|Oxidation|ac", reference_combined$PrecursorID, invert=TRUE),]







# unidentified_peptides_latent <- unidentified_peptides[, grep("dim", colnames(unidentified_peptides))]
#k = 10



reference_combined_sub <- reference_combined[reference_combined$Species %in% c("HeLa","Yeast"), ] # c("HeLa","Human","Yeast")
reference_latent <- reference_combined_sub[, grep("dim", colnames(reference_combined_sub))]
#reference_latent <- t(apply(reference_latent, 1, FUN=function(x) x/sqrt(sum(x^2))))
reference_charge <- reference_combined_sub$Charge
reference_ident_labels <- reference_combined_sub$PrecursorID
reference_ident_species <- reference_combined_sub$Species



study_embedding <- reference_combined[reference_combined$Species %in% c("Human","Yeast"), ] # c("HeLa","Human","Yeast")
study_latent <- study_embedding[, grep("dim", colnames(study_embedding))]
#study_latent <- t(apply(study_latent, 1, FUN=function(x) x/sqrt(sum(x^2)) ))
study_charge <- study_embedding$Charge
study_ident_labels <- study_embedding$PrecursorID
study_ident_species <- study_embedding$Species



tcells_evidence_dedupped <- tcells_evidence[, c("Raw.file","PrecursorID")]
tcells_evidence_dedupped <- tcells_evidence_dedupped[!duplicated(tcells_evidence_dedupped),]
# tcells_evidence_dedupped <- tcells_evidence_dedupped[grep("ox|Deamidation|Acetyl|Oxidation|ac", tcells_evidence_dedupped$PrecursorID, invert=TRUE),]
```

```{r}
computeStats <- function(thr, k){
  
  false_transfer_rate <- c()
  # coverage_per_run <- c()
  total_idents_per_run_after_transfer <- c()
  number_new_ident <- c()
  coverage_per_run_after_transfer <- c()
  coverage_per_run_before_transfer <- c()
  ident_list <- list()
  
  itr = 1
  
  for (run in unique(tcells_evidence_dedupped$Raw.file)){
    
    message(run)
    missing_idents <- setdiff(tcells_evidence_dedupped$PrecursorID,
                              tcells_evidence_dedupped$PrecursorID[tcells_evidence_dedupped$Raw.file == run])
  
    latent_study <- study_latent[study_embedding$PrecursorID %in% missing_idents,]
    s_charge <- study_charge[study_embedding$PrecursorID %in% missing_idents]
    s_ident_labels <- study_ident_labels[study_embedding$PrecursorID %in% missing_idents]
    s_ident_species <- study_ident_species[study_embedding$PrecursorID %in% missing_idents]
  
  
    run_query_peptides <- unidentified_peptides[unidentified_peptides$Raw.file %in% run,]
  
    run_query_peptides_latent <- run_query_peptides[, grep("dim", colnames(run_query_peptides))]
    #run_query_peptides_latent <- t(apply(run_query_peptides_latent, 1, FUN=function(x) x/sqrt(sum(x^2))))
    query_feature_charges <- run_query_peptides$Charge
    run_query_peptides_intensity <- run_query_peptides$Intensity
  
  
    knn_prototypes <- FNN::get.knnx(

        latent_study,
        run_query_peptides_latent,
      k = k) 
  
    probs <- exp(-0.5*((knn_prototypes$nn.dist^2)/matrixStats::rowSds(knn_prototypes$nn.dist^2)))
    # probs <- 1 - knn_prototypes$nn.dist^2
    ww <- matrix(s_charge[knn_prototypes$nn.index], nrow = nrow(probs), ncol = ncol(probs))
    charge <- matrix(query_feature_charges, nrow = nrow(ww), ncol = ncol(ww), byrow = FALSE)
    w <- ifelse(ww==charge, 1, 0)
  
  
  
  
  
    transferred_idents <- matrix(s_ident_labels[knn_prototypes$nn.index], 
                               nrow = nrow(probs), ncol = ncol(probs))
    transferred_species <- matrix(s_ident_species[knn_prototypes$nn.index], 
                                nrow = nrow(probs), ncol = ncol(probs))


    # probs <- w*probs
    # probs <- probs/rowSums(probs)
    # probs[!is.finite(probs)] <- 0

    transferred_idents[w==0] <- "other"
    transferred_species[w==0] <- "other"


    unmapped_queries <- (rowSums(probs < thr) == k)
    
    false_transfers_co <- which(rowSums(probs >= thr & transferred_species == c("Yeast") ) > 1)
    length(false_transfers_co)
  
  
    correct_transfers <-  (rowSums(probs >= thr & (transferred_species == "Human" | transferred_species == "HeLa") )> 2)
    correct_transfers_run_names <- run_query_peptides$Raw.file[correct_transfers]
    correct_transfer_idents <- transferred_idents[correct_transfers,]
    correct_transfer_idents <- apply(correct_transfer_idents,1, FUN=function(x) {
      z <- table(x)
      z <- z[!grepl("other", names(z))]
      names(z)[which.max(z)]}
      )
  
    #correct_transfer_idents <- gsub("__","_",correct_transfer_idents)
    transfer_idents <- do.call(cbind, list(correct_transfers_run_names, correct_transfer_idents,
                                           run_query_peptides_intensity[correct_transfers]))
    transfer_idents <- data.frame(transfer_idents)
    colnames(transfer_idents) <- c("Raw.file","PrecursorID","Intensity")
    # transfer_idents$PrecursorID <- gsub("__","_", transfer_idents$PrecursorID)
  
    
    
    ### computation of false transfers-------
    
    # false_transfer_rate[itr] <- length(false_transfers)
    
    query_feature_charges <- run_query_peptides$Charge[unmapped_queries]
    unmapped_queries_latent <- run_query_peptides_latent[unmapped_queries,]
    unmapped_queries_inetnsity <- run_query_peptides_intensity[unmapped_queries]
    
    if(nrow(unmapped_queries_latent) > 0 ) {
      
      
      ex_prototypes <- FNN::get.knnx(

        reference_latent,
        unmapped_queries_latent,
      k = k) 
  
    ex_probs <- exp(-0.5*((ex_prototypes$nn.dist^2)/matrixStats::rowSds(ex_prototypes$nn.dist^2)))
    # ex_probs <- 1 - ex_prototypes$nn.dist^2
    ww2 <- matrix(reference_charge[ex_prototypes$nn.index], nrow = nrow(ex_probs), ncol = ncol(ex_probs))
    charge_ex <- matrix(query_feature_charges, nrow = nrow(ww2), ncol = ncol(ww2), byrow = FALSE)
    w2 <- ifelse(ww2==charge_ex, 1, 0)
  
  
  
  
  
    transferred_idents <- matrix(reference_ident_labels[ex_prototypes$nn.index], 
                               nrow = nrow(ex_probs), ncol = ncol(ex_probs))
    transferred_species <- matrix(reference_ident_species[ex_prototypes$nn.index], 
                                nrow = nrow(ex_probs), ncol = ncol(ex_probs))


    #ex_probs <- w2*ex_probs
    #ex_probs <- ex_probs/rowSums(ex_probs)
    # ex_probs[!is.finite(ex_probs)] <- 0

    transferred_idents[w2==0] <- "other"
    transferred_species[w2==0] <- "other"
    
    
    false_transfers <- which(rowSums(ex_probs >= thr & transferred_species == c("Yeast")) > 1)
    length(false_transfers)
    
    
    
    new_transfers <- which(rowSums(ex_probs >= thr & (transferred_species == "HeLa") ) > 1)
    length(new_transfers)
    
    if(length(new_transfers) > 0){
      
      new_transfers_run_names <- run_query_peptides$Raw.file[unmapped_queries][new_transfers]
      new_transfer_idents <- transferred_idents[new_transfers,, drop=FALSE]
      new_transfer_idents <- apply(new_transfer_idents,1, FUN=function(x) {
        z <- table(x)
        z <- z[!grepl("other", names(z))]
        names(z)[which.max(z)]
        }
      )
  
      new_transfer_idents <- gsub("__","_", new_transfer_idents)
      transfer_idents2 <- do.call(cbind, list(new_transfers_run_names, new_transfer_idents,
                                              unmapped_queries_inetnsity[new_transfers]))
      transfer_idents2 <- data.frame(transfer_idents2)
      colnames(transfer_idents2) <- c("Raw.file","PrecursorID","Intensity")
      # transfer_idents2$PrecursorID <- gsub("__","_", transfer_idents2$PrecursorID)
  
      total_transferred_idents <- rbind(transfer_idents2, transfer_idents)
      number_new_ident[itr] <- length(setdiff(transfer_idents2$PrecursorID, tcells_evidence_dedupped$PrecursorID))
    } else {
      total_transferred_idents <- transfer_idents
      number_new_ident[itr] <- 0
    }
    
     
    false_transfers <- c(false_transfers, false_transfers_co)
    false_transfer_rate[itr] <- length(false_transfers)/length(union(total_transferred_idents$PrecursorID,
                                                                      tcells_evidence_dedupped$PrecursorID[tcells_evidence_dedupped$Raw.file %in% run]))
     
    } else{
      
      
      
      total_transferred_idents <- transfer_idents
      false_transfer_rate[itr] <- length(false_transfers_co)/length(union(total_transferred_idents$PrecursorID,
                                                                      tcells_evidence_dedupped$PrecursorID[tcells_evidence_dedupped$Raw.file %in% run]))
      number_new_ident[itr] <- 0
      
    }
    
     
    
    
    
    # need to store raw file, precursor and Intensity
    all_idents <- rbind(cbind(tcells_evidence[tcells_evidence$Raw.file %in% run, 
                                        c("Raw.file","PrecursorID","Intensity")],
                              type = "TIMS-MULTI-MSMS"),
                        cbind(total_transferred_idents, type = "PIP")
    )
    
    all_idents_in_run <- union(total_transferred_idents$PrecursorID,
                               tcells_evidence_dedupped$PrecursorID[tcells_evidence_dedupped$Raw.file %in% run])
    
    coverage_per_run_after_transfer[itr] <- length(intersect(all_idents_in_run, tcells_evidence_dedupped$PrecursorID))/ length(unique(tcells_evidence_dedupped$PrecursorID))
    
    
    coverage_per_run_before_transfer[itr] <- length(intersect(tcells_evidence_dedupped$PrecursorID[tcells_evidence_dedupped$Raw.file %in% run], tcells_evidence_dedupped$PrecursorID))/ length(unique(tcells_evidence_dedupped$PrecursorID))
    
    

    total_idents_per_run_after_transfer[itr] <- length(all_idents_in_run)
    ident_list[[itr]] <- data.frame(all_idents)

   
    
    itr = itr + 1
     
    
  
  }
  
  ALL_IDENTS <- do.call(rbind, ident_list)
  return(list("threshold" = rep(thr, length(unique(tcells_evidence_dedupped$Raw.file))), 
              "false_transfer_rate" = false_transfer_rate, 
                         #"median_coverage" = med_cov_per_run, 
              "coverage_before_transfer" = coverage_per_run_before_transfer,
              "coverage_after_transfer" = coverage_per_run_after_transfer,
              "number_new_idents" = number_new_ident,
              "total_idents_per_run_after_PIP" = total_idents_per_run_after_transfer,
              "identifications" = ALL_IDENTS))
}
```

```{r eval = FALSE}
computeStats(0.05, k = 10)


computeStats(0.2)

computeStats(0.8)
computeStats(0, k = 10)
```


```{r}

devtools::load_all("/stornext/General/data/academic/lab_davis/prot/benchmarking/msImpute/")
data <- read.delim("~/ion_mobility/PXD023049/txt/evidence.txt", 
                   stringsAsFactors = FALSE)


table(data$Type)

data$PeptideID <- paste0(data$Modified.sequence, data$Charge)
data$matrix.row.id <- paste(data$PeptideID, data$Leading.Razor.Protein, sep ="_")


length(unique(data$PeptideID))


genes <- data[,c("PeptideID","matrix.row.id", "Leading.razor.protein")]
genes <- genes[!duplicated(genes),]






tcells_pip_k10_cut005 <- computeStats(0, k = 10)

z <- tcells_pip_k10_cut005$identifications
table(z$type)
dim(data)


z$Intensity <- as.numeric(z$Intensity)

y_pip <- evidenceToMatrix(z, peptide_id = "PrecursorID")

# y_pip["_AAAANLCPGDVILAIDGFGTESMTHADAQDR_3",]
# z[z$PrecursorID %in% "_AAAANLCPGDVILAIDGFGTESMTHADAQDR_3",]


median(colSums(!is.na(y_pip)))
summary(colSums(!is.na(y_pip)))




y_noMBR <- evidenceToMatrix(data)
# what is median identifications per run
median(colSums(!is.na(y_noMBR)))
summary(colSums(!is.na(y_noMBR)))


dim(y_noMBR)
dim(y_pip)


# drop modifications
y_noMBR <- y_noMBR[grep("[a-z]+", rownames(y_noMBR), invert = TRUE),]
y_pip <- y_pip[grep("[a-z]+", rownames(y_pip), invert = TRUE),]

## filter out some rows/entries ----

y_noMBR <- y_noMBR[rowSums(!is.na(y_noMBR)) > 2,]
y_pip <- y_pip[rowSums(!is.na(y_pip)) > 2,]

mean(complete.cases(y_noMBR))
mean(complete.cases(y_pip))
mean(complete.cases(y_pip[rownames(y_noMBR),]))



missing_peptides <- rownames(y_noMBR)[!complete.cases(y_noMBR[,1:3]) & complete.cases(y_noMBR[,4:6])]
length(missing_peptides)

library(pheatmap)

z1 <- t(scale(t(log2(y_noMBR))))
z2 <- t(scale(t(log2(y_pip))))

# z1 <- log2(y_noMBR)
# z2 <- log2(y_pip)




pheatobj <- pheatmap(z2[missing_peptides,], show_rownames = FALSE,
         treeheight_row = 0,
         treeheight_col = 0, 
         labels_col = gsub("(.*)_(.*)_(.*)_(.*)_(.*)", "\\1_\\2", colnames(z2)), 
         main = "Peptideprotonet + PIP",
         cluster_cols = FALSE,
         cluster_rows = TRUE)



 pheatmap(z1[missing_peptides,][pheatobj$tree_row$order,], show_rownames = FALSE, # [pheatobj$tree_row$order,]
         treeheight_row = 0, 
         treeheight_col = 0, 
         labels_col = gsub("(.*)_(.*)_(.*)_(.*)_(.*)", "\\1_\\2", colnames(z1)), 
         main = "MaxQuant",
         cluster_cols = FALSE,
         cluster_rows = FALSE)

```


```{r}
############# Tabularise results for different cut-offs

results_k10 <- list()
itr = 1
for (thr in c(0, 0.01, 0.05, 0.2,0.5, 0.8)){
  res <- computeStats(thr, k = 10)
  results_k10[[itr]] <- list("threshold" = thr, "false_transfer_rate" = median(res$false_transfer_rate), 
                         "mean_coverage" = median(res$coverage_before_transfer), 
                         "mean_coverage_after_transfer" = mean(res$coverage_after_transfer),
                         "max_coverage_after_transfer" = max(res$coverage_after_transfer),
                         "N_new_idents" = round(median(res$number_new_idents)),
                         "median_idents_per_run_after_PIP" = round(median(res$total_idents_per_run_after_PIP)),
                         "identifications" = res$identifications)
  
  itr = itr + 1
  
}

coverage_results <- lapply(results_k10, FUN=function(x)  x[!grepl("identifications", names(x))])

(dt_k10 <- data.frame(do.call(rbind, coverage_results)))
dt_k10 <- data.frame(round(data.matrix(dt_k10),3))





results_5k <- list()
itr = 1
for (thr in c(0, 0.01, 0.05, 0.2,0.5, 0.8)){
  res <- computeStats(thr, k = 5)
  results_5k[[itr]] <- list("threshold" = thr, "false_transfer_rate" = median(res$false_transfer_rate), 
                         "mean_coverage" = median(res$coverage_before_transfer), 
                         "mean_coverage_after_transfer" = mean(res$coverage_after_transfer),
                         "max_coverage_after_transfer" = max(res$coverage_after_transfer),
                         "N_new_idents" = round(median(res$number_new_idents)),
                         "median_idents_per_run_after_PIP" = round(median(res$total_idents_per_run_after_PIP)),
                         "identifications" = res$identifications)
  
  itr = itr + 1
  
}

coverage_results <- lapply(results_5k, FUN=function(x)  x[!grepl("identifications", names(x))])

(dt_k5 <- data.frame(do.call(rbind, coverage_results)))
dt_k5 <- data.frame(round(data.matrix(dt_k5),3))

dt_k10_tcells <- dt_k10
dt_k5_tcells <- dt_k5

# save(dt_k10_tcells, dt_k5_tcells, file = "tcells_exosome_peptideprotonet_evals.RData")
```
















## old analyses here on

```{r}
dt %>%
  kbl(caption = "False transfer rate and peptide coverage per run",
      col.names = c("Threshold", "False transfer rate", "Mean coverage", "Mean coverage after PIP", 
                    "Max coverage after PIP", 
                    "Number new identifications", "Median identifications per run"),
      booktabs = TRUE) %>%
  kable_classic(full_width = F, html_font = "Cambria")
```


```{r}
## older code where ids are propagated by one-pass approach

k = 10

knn_prototypes <- FNN::get.knnx(

      
      reference_latent,
      unidentified_peptides_latent,
      k = k) # nsamples - 1


    
probs <- exp(-0.5*((knn_prototypes$nn.dist^2)/matrixStats::rowSds(knn_prototypes$nn.dist^2)))
# probs <- knn_prototypes$nn.index


ww <- matrix(reference_charge[knn_prototypes$nn.index], nrow = nrow(probs), ncol = ncol(probs))
charge <- matrix(query_feature_charges, nrow = nrow(ww), ncol = ncol(ww), byrow = FALSE)
w <- ifelse(ww==charge, 1, 0)

transferred_idents <- matrix(reference_ident_labels[knn_prototypes$nn.index], nrow = nrow(probs), ncol = ncol(probs))
transferred_species <- matrix(reference_ident_species[knn_prototypes$nn.index], nrow = nrow(probs), ncol = ncol(probs))






probs <- w*probs

transferred_idents[w==0] <- "other"
transferred_species[w==0] <- "other"




table(rowSums(transferred_species == "Yeast") == 15)
table(rowSums(transferred_species == "Yeast") > 10)
table(rowSums(transferred_species == "Yeast") > 7)

# which of the peptides with high p of being identified as yeast share a neighbourhood with an identified peptide in the same run?

# ## mapping between identified peptides and unidentified peptides by closeness of their LC-MS features
# dentified_peptides <- FNN::get.knnx(identified_peptides[, grep("Intensity", lc_ms_anchors, invert=TRUE, value = TRUE)], 
#                                     unidentified_peptides[, grep("Intensity", lc_ms_anchors, invert=TRUE, value = TRUE)], 
#                                     k=3)
# 
# 
# 
# 
# probs <- exp(-0.5*((dentified_peptides$nn.dist^2)/matrixStats::rowSds(dentified_peptides$nn.dist^2)))

# probs <- exp(-0.5*((dentified_peptides$nn.dist^2)))
# probs <- probs/rowSums(probs)

hist(probs)
hist(probs[,1])
hist(probs/rowSums(probs))

# table(probs[,1] > 0.5 & rowSums(transferred_species == "Yeast") > 7)
# table(probs[,1] > 0.8 & rowSums(transferred_species == "Yeast") > 7)

results <- list()
itr = 1
for (thr in c(0,0.01,0.05, 0.2,0.5, 0.8)){
  ## compute false transfers as ratio of yeast transfers to human transfers per run 
  # false_transfers <- (probs[,1] >= thr & rowSums(transferred_species == "Yeast" | transferred_species == "Ecoli" |
  #                                                  transferred_species == "Drosophila" | transferred_species == "CElegans") > 7)
  
  
  
  
  unmapped_queries <- (rowSums(probs < thr) == k)
  
  
  correct_transfers <-  (rowSums(probs >= thr & (transferred_species == "Human" | transferred_species == "HeLa") )> 7)

  correct_transfers_run_names <- unidentified_peptides$Raw.file[correct_transfers]
  false_transfers_run_names <- unidentified_peptides$Raw.file[false_transfers]
  # total_transfers_run_names <- unidentified_peptides$Raw.file[probs[,1] > 0.5]




  correct_transfer_idents <- transferred_idents[correct_transfers,]
  correct_transfer_idents <- apply(correct_transfer_idents,1, FUN=function(x) {
    z <- table(x)
    names(z)[which.max(z)]}
    )
  
  
  # correct_transfer_idents <- unlist(correct_transfer_idents)
  correct_transfer_idents <- gsub("__","_",correct_transfer_idents)

  # transfer_idents <- data.frame(Raw.file = correct_transfers_run_names,
  #                            PrecursorID = correct_transfer_idents)
  
  
  transfer_idents <- do.call(cbind, list(correct_transfers_run_names, correct_transfer_idents))
  transfer_idents <- data.frame(transfer_idents)
  colnames(transfer_idents) <- c("Raw.file","PrecursorID")
  transfer_idents$PrecursorID <- gsub("__","_", transfer_idents$PrecursorID)


  
  false_transfers <- (rowSums(probs >= thr & transferred_species == "Yeast" ) > 7)

  if (sum(false_transfers) == 0) {
    ftr <- 0
  }else{
    ftr <- median(table(false_transfers_run_names)/(table(tcells_evidence_dedupped_with_transfer$Raw.file)))
  }
  
  
  


  ## coverage results
  all_idents <- unique(tcells_evidence_dedupped$PrecursorID)

  coverage_per_run <- c()

  for (run in unique(tcells_evidence$Raw.file)){
    z <- sum(tcells_evidence_dedupped$PrecursorID[tcells_evidence_dedupped$Raw.file %in% run] %in% all_idents)/length(all_idents)
   coverage_per_run <- c(coverage_per_run, z)
  }
  med_cov_per_run <- median(coverage_per_run)



  coverage_per_run_after_transfer <- c()
  for (run in unique(tcells_evidence$Raw.file)){
    z <- length(intersect(tcells_evidence_dedupped_with_transfer$PrecursorID[tcells_evidence_dedupped_with_transfer$Raw.file %in% run] ,all_idents))/length(all_idents)
    coverage_per_run_after_transfer <- c(coverage_per_run_after_transfer, z)
  }
  
  med_cov_after_transfer <- median(coverage_per_run_after_transfer)  
  
  
  
  ident_ratios_per_run <- c()
  
  for (run in unique(tcells_evidence$Raw.file)){
    z <- length(setdiff(transfer_idents$PrecursorID, tcells_evidence_dedupped$PrecursorID))/length(unique(tcells_evidence_dedupped$PrecursorID))
    ident_ratios_per_run <- c(ident_ratios_per_run, z)
  }


  ident_ratios_per_run <- median(ident_ratios_per_run)
  
  
  
  total_idents_per_run_after_transfer <- c()
  
  for (run in unique(tcells_evidence$Raw.file)){
    z <- length(unique(tcells_evidence_dedupped_with_transfer$PrecursorID))
    total_idents_per_run_after_transfer <- c(total_idents_per_run_after_transfer, z)
  }


  med_total_idents_after_transfer <- median(total_idents_per_run_after_transfer)
  
  results[[itr]] <- list("threshold" = thr, "false_transfer_rate" = ftr, 
                         "median_coverage" = med_cov_per_run, 
                         "median_coverage_after_transfer" = med_cov_after_transfer,
                         "prop_new_idents" = ident_ratios_per_run,
                         "median_idents_per_run" = med_total_idents_after_transfer)
  
  itr = itr + 1

}

(dt <- data.frame(do.call(rbind, results)))

library(kableExtra)

dt <- data.frame(round(data.matrix(dt),3))


dt %>%
  kbl(caption = "False transfer rate and peptide coverage per run",
      col.names = c("Threshold", "False transfer rate", "Median coverage", "Median coverage after PIP", 
                    "Proportion new identifications", "Median identifications per run"),
      booktabs = TRUE) %>%
  kable_classic(full_width = F, html_font = "Cambria")
```
